version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: news-aggregator-api-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy # Ensures DB is fully ready before starting

  db:
    image: mysql:8.0
    container_name: news-aggregator-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: news_aggregator
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
     - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      retries: 5
      timeout: 5s

  nginx:
    image: nginx:alpine
    container_name: news-aggregator-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app # Ensure Laravel app is running
    networks:
      - app-network

networks:
  app-network:

volumes:
  db-data:
